version: '3'
services:
    registry:
        image: registry:2.6.2
        ports:
            - '5000:5000'
        volumes:
            - ./registry:/var/lib/registry
            - ./config.yml:/etc/docker/registry/config.yml
        restart: always
    redis:
        image: redis:4.0.6-alpine
        restart: always